--[[ Driver Manager System File ]]--
--[[ This gets loaded on startup! DO NOT EDIT THIS FILE OR FrostOS WILL BECOME CORRUPT ]]--
os.loadAPI("/.frostos/apis/logger")
local FileList = fs.list("/.frostos/drivers")

for _, file in ipairs(FileList) do
  os.loadAPI("/.frostos/drivers/" .. file)
  logger.info("DriverMan: Added Driver: ".. file)
end
