--[[ Driver Manager System File ]]--
--[[ This gets loaded on startup! DO NOT EDIT THIS FILE OR FrostOS WILL BECOME CORRUPT ]]--
local log = "/.frostos/logs/driverman.log"
os.loadAPI("/.frostos/apis/logger")
local FileList = fs.list("/.frostos/drivers")

for _, file in ipairs(FileList) do
  os.loadAPI("/.frostos/drivers/" .. file)
  logger.info(log, "DriverMan: Added Driver: ".. file)
end
